version: '3.1'
services:
  frontend:
    container_name: FRONTEND
    image: carone/frontend-image:latest
    ports:
      - 3000:3000

  backend:
    container_name: BACKEND
    image: carone/backend-image:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - db

  db:
    container_name: DB
    image: carone/db-image:latest
    restart: always
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  notused: